language: python
install:
    - pip install tox
script:
    - tox
matrix:
    include:
        - python: 2.7
          env:
              - TOXENV=py27
        - python: 3.4
          env:
              - TOXENV=py34
        - python: 3.5
          env:
              - TOXENV=py35
sudo: required
dist: trusty
